services:
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - 80:80
  
  backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - db:/api/storage
  
volumes:
  db:
    name: backend-db

