services:
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data

  frontend:
    restart: unless-stopped
    build: ./frontend
  
  backend:
    restart: unless-stopped
    build: ./backend
    environment:
      - ORIGIN=https://ilovequt.lol
    volumes:
      - db:/api/storage
  
volumes:
  db:
    name: backend-db
  caddy:
    name: caddy-data
